package FileAssert {
    part def Program {
        doc /* Entry point and execution orchestrator. */

        comment sourceRef /* Source: src/DemaConsulting.FileAssert/Program.cs */
        comment testRef /* Test: test/DemaConsulting.FileAssert.Tests/ProgramTests.cs */
        comment designRef /* Design: docs/design/file-assert/program.md */
        comment verificationRef /* Verification: docs/verification/file-assert/program.md */
        comment reqRef /* Requirements: docs/reqstream/file-assert/program.yaml */
    }
}
