package FileAssert {
    part def FileAssertTextAssert {
        doc /* Text content assertions. */

        comment sourceRef /* Source: src/DemaConsulting.FileAssert/Modeling/FileAssertTextAssert.cs */
        comment testRef /* Test: test/DemaConsulting.FileAssert.Tests/Modeling/FileAssertTextAssertTests.cs */
        comment designRef /* Design: docs/design/file-assert/modeling/file-assert-text-assert.md */
        comment verificationRef /* Verification: docs/verification/file-assert/modeling/file-assert-text-assert.md */
        comment reqRef /* Requirements: docs/reqstream/file-assert/modeling/file-assert-text-assert.yaml */
    }
}
