package FileAssert {
    part def FileAssertRule {
        doc /* Abstract content validation rule hierarchy. */

        comment sourceRef /* Source: src/DemaConsulting.FileAssert/Modeling/FileAssertRule.cs */
        comment testRef /* Test: test/DemaConsulting.FileAssert.Tests/Modeling/FileAssertRuleTests.cs */
        comment designRef /* Design: docs/design/file-assert/modeling/file-assert-rule.md */
        comment verificationRef /* Verification: docs/verification/file-assert/modeling/file-assert-rule.md */
        comment reqRef /* Requirements: docs/reqstream/file-assert/modeling/file-assert-rule.yaml */
    }
}
