package FileAssert {
    part def FileAssertHtmlAssert {
        doc /* HTML document assertions (HtmlAgilityPack). */

        comment sourceRef /* Source: src/DemaConsulting.FileAssert/Modeling/FileAssertHtmlAssert.cs */
        comment testRef /* Test: test/DemaConsulting.FileAssert.Tests/Modeling/FileAssertHtmlAssertTests.cs */
        comment designRef /* Design: docs/design/file-assert/modeling/file-assert-html-assert.md */
        comment verificationRef /* Verification: docs/verification/file-assert/modeling/file-assert-html-assert.md */
        comment reqRef /* Requirements: docs/reqstream/file-assert/modeling/file-assert-html-assert.yaml */
    }
}
