package FileAssert {
    part def FileAssertYamlAssert {
        doc /* YAML document assertions (YamlDotNet). */

        comment sourceRef /* Source: src/DemaConsulting.FileAssert/Modeling/FileAssertYamlAssert.cs */
        comment testRef /* Test: test/DemaConsulting.FileAssert.Tests/Modeling/FileAssertYamlAssertTests.cs */
        comment designRef /* Design: docs/design/file-assert/modeling/file-assert-yaml-assert.md */
        comment verificationRef /* Verification: docs/verification/file-assert/modeling/file-assert-yaml-assert.md */
        comment reqRef /* Requirements: docs/reqstream/file-assert/modeling/file-assert-yaml-assert.yaml */
    }
}
