package OtsDependencies {
    doc /* Off-the-shelf (OTS) dependencies used by FileAssert. */

    part def YamlDotNet {
        doc /* OTS: YamlDotNet. */

        comment designRef /* Design: docs/design/ots/yamldotnet.md */
        comment verificationRef /* Verification: docs/verification/ots/yamldotnet.md */
        comment reqRef /* Requirements: docs/reqstream/ots/yamldotnet.yaml */
    }

    part def PdfPig {
        doc /* OTS: PdfPig. */

        comment designRef /* Design: docs/design/ots/pdfpig.md */
        comment verificationRef /* Verification: docs/verification/ots/pdfpig.md */
        comment reqRef /* Requirements: docs/reqstream/ots/pdfpig.yaml */
    }

    part def HtmlAgilityPack {
        doc /* OTS: HtmlAgilityPack. */

        comment designRef /* Design: docs/design/ots/htmlagilitypack.md */
        comment verificationRef /* Verification: docs/verification/ots/htmlagilitypack.md */
        comment reqRef /* Requirements: docs/reqstream/ots/htmlagilitypack.yaml */
    }

    part def FileSystemGlobbing {
        doc /* OTS: FileSystemGlobbing. */

        comment designRef /* Design: docs/design/ots/filesystemglobbing.md */
        comment verificationRef /* Verification: docs/verification/ots/filesystemglobbing.md */
        comment reqRef /* Requirements: docs/reqstream/ots/filesystemglobbing.yaml */
    }
}
