package FileAssert {
    part def DirectoryFileContainer {
        doc /* Filesystem implementation of IFileContainer. */

        comment sourceRef /* Source: src/DemaConsulting.FileAssert/Utilities/DirectoryFileContainer.cs */
        comment testRef /* Test: test/DemaConsulting.FileAssert.Tests/Utilities/IFileContainerTests.cs */
        comment designRef /* Design: docs/design/file-assert/utilities/directory-file-container.md */
        comment verificationRef /* Verification: docs/verification/file-assert/utilities/directory-file-container.md */
        comment reqRef /* Requirements: docs/reqstream/file-assert/utilities/directory-file-container.yaml */
    }
}
