package FileAssert {
    part def TemporaryDirectory {
        doc /* Disposable temporary directory utility. */

        comment sourceRef /* Source: src/DemaConsulting.FileAssert/Utilities/TemporaryDirectory.cs */
        comment testRef /* Test: test/DemaConsulting.FileAssert.Tests/Utilities/TemporaryDirectoryTests.cs */
        comment designRef /* Design: docs/design/file-assert/utilities/temporary-directory.md */
        comment verificationRef /* Verification: docs/verification/file-assert/utilities/temporary-directory.md */
        comment reqRef /* Requirements: docs/reqstream/file-assert/utilities/temporary-directory.yaml */
    }
}
