package FileAssert {
    part def ZipFileContainer {
        doc /* Zip archive implementation of IFileContainer. */

        comment sourceRef /* Source: src/DemaConsulting.FileAssert/Utilities/ZipFileContainer.cs */
        comment testRef /* Test: test/DemaConsulting.FileAssert.Tests/Utilities/IFileContainerTests.cs */
        comment designRef /* Design: docs/design/file-assert/utilities/zip-file-container.md */
        comment verificationRef /* Verification: docs/verification/file-assert/utilities/zip-file-container.md */
        comment reqRef /* Requirements: docs/reqstream/file-assert/utilities/zip-file-container.yaml */
    }
}
