package FileAssert {
    part def Validation {
        doc /* Self-validation test runner. */

        comment sourceRef /* Source: src/DemaConsulting.FileAssert/SelfTest/Validation.cs */
        comment testRef /* Test: test/DemaConsulting.FileAssert.Tests/SelfTest/ValidationTests.cs */
        comment designRef /* Design: docs/design/file-assert/selftest/validation.md */
        comment verificationRef /* Verification: docs/verification/file-assert/selftest/validation.md */
        comment reqRef /* Requirements: docs/reqstream/file-assert/selftest/validation.yaml */
    }
}
